require 'active_record'
ActiveRecord::Base.establish_connection :adapter => "sqlite3",
                                        :database => "dbfile"

# Create a database table that contains tasks
ActiveRecord::Base.connection.create_table :tasks do |t|
  t.string  :description
  t.boolean :completed
end

# Define an empty 'Task' class that inherits from ActiveRecord::Base
class Task < ActiveRecord::Base; end

task = Task.new
# These ~attribute methods~ below are automatically generated by Active Record 
# by looking at the columns of the 'tasks' table
task.description = 'Clean up garage'
task.completed = true
task.save

task.description # => "Clean up garage"
task.completed? # => true

# Attributes that are not backed by a db column, such as a calculated field
my_query = "tasks.*, (description like '%garage%') as heavy_job"
task = Task.find(:first, :select => my_query)
task.heavy_job? # => true
